# Generated by Django 2.2.5 on 2020-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_exam_name', models.CharField(max_length=50)),
                ('student_code', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=50)),
                ('student_question_code', models.TextField(blank=True)),
                ('student_options_answer', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
